notification:
    resource: "@NotificationBundle/Resources/config/routing.yml"
    prefix:   /Notifications

faqs:
    resource: "@FaqsBundle/Resources/config/routing.yml"
    prefix:   /Faqs


equipement:
    resource: "@EquipementBundle/Resources/config/routing.yml"
    prefix:   /Equipement

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix:  /message

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix:  /notifications